### ISSUE TITLE
Mistake in tutorial: bad library in build.gradle

### ISSUE THREAD

**Issue by micdmy** [sebsto/amplify-ios-getting-started#3]
In 4 step of tutorial: https://aws.amazon.com/getting-started/hands-on/build-android-app-amplify/module-four/
In substep: "Add API Client Library to the Android Studio Project"

You instruct to add dependencies:

`dependencies {
    implementation 'com.amplifyframework:aws-api:1.4.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.4.0'
}`

This dependencies are already added in previous step.
However, aws-api library is missing:

`implementation 'com.amplifyframework:aws-api:1.17.1'`

**Comment by sebsto** [comment]
opened in wrong repo, I moved it to https://github.com/sebsto/amplify-android-getting-started/issues
